---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_mariadb"
      tags:
        - "labocbz.install_mariadb"
      vars:
        install_mariadb__confs_path: "{{ inv_install_mariadb__confs_path }}"
        install_mariadb__config_path: "{{ inv_install_mariadb__config_path }}"
        install_mariadb__ssl_path: "{{ inv_install_mariadb__ssl_path }}"
        install_mariadb__log_path: "{{ inv_install_mariadb__log_path }}"
        install_mariadb__port: "{{ inv_install_mariadb__port }}"
        install_mariadb__bind_address: "{{ inv_install_mariadb__bind_address }}"
        install_mariadb__server_id: "{{ inv_install_mariadb__server_id }}"
        install_mariadb__max_connections: "{{ inv_install_mariadb__max_connections }}"
        install_mariadb__innodb_buffer_pool_size: "{{ inv_install_mariadb__innodb_buffer_pool_size }}"
        install_mariadb__general_log_file: "{{ inv_install_mariadb__general_log_file }}"
        install_mariadb__general_log: "{{ inv_install_mariadb__general_log }}"
        install_mariadb__log_error: "{{ inv_install_mariadb__log_error }}"
        install_mariadb__log_bin: "{{ inv_install_mariadb__log_bin }}"
        install_mariadb__expire_logs_days: "{{ inv_install_mariadb__expire_logs_days }}"
        install_mariadb__max_binlog_size: "{{ inv_install_mariadb__max_binlog_size }}"
        install_mariadb__ssl: "{{ inv_install_mariadb__ssl }}"
        install_mariadb__ssl_client_auth: "{{ inv_install_mariadb__ssl_client_auth }}"
        install_mariadb__ssl_ca: "{{ inv_install_mariadb__ssl_ca }}"
        install_mariadb__ssl_cert: "{{ inv_install_mariadb__ssl_cert }}"
        install_mariadb__ssl_key: "{{ inv_install_mariadb__ssl_key }}"
        install_mariadb__charset: "{{ inv_install_mariadb__charset }}"
        install_mariadb__collation: "{{ inv_install_mariadb__collation }}"
        install_mariadb__galera_cluster: "{{ inv_install_mariadb__galera_cluster }}"
        install_mariadb__galera_node_list: "{{ inv_install_mariadb__galera_node_list }}"
        install_mariadb__galera_clustername: "{{ inv_install_mariadb__galera_clustername }}"
        install_mariadb__galera_node_name: "{{ inv_install_mariadb__galera_node_name }}"
        install_mariadb__galera_node_address: "{{ inv_install_mariadb__galera_node_address }}"
        install_mariadb__galera_cluster_seed_host: "{{ inv_install_mariadb__galera_cluster_seed_host }}"
        install_mariadb__secure_root_password: "{{ inv_install_mariadb__secure_root_password }}"
      ansible.builtin.include_role:
        name: "labocbz.install_mariadb"
